bosses:
  devil_chan:
    energy: 3
    rows: 3
    columns: 4
    hp: 50
    basic: "Devilish stab"
    special: "A neat little hack"
    phrases:
      - "Here's a neat little hack"
  ms_g:
    energy: 4
    rows: 5
    columns: 4
    hp: 100
    basic: "Roast"
    special: "Send you to Siberia"
    phrases:
      - "Sean!"
      - "One of them is a woman, the other has an Indian accent if you're into it"
      - "I'll only give you 100 if you’re one of my favourite students"
      - "Do it on Repl"
      - "Go to Siberia!"
      - "Don't ask me, use your brain"
      - "Troubleshoot it"
      - "Gosh"
  mr_phone:
    energy: 5
    rows: 7
    columns: 4
    hp: 200
    basic: "Disappointment"
    special: "Emotional damage"
    kill: "Thinking question"
    phrases:
      - "You need to touch grass"
      - "My son could beat you at this game"
      - "Easy choices hard life, hard choices easy life"
      - "It's only awkward if you make it awkward"
      - "Almost everything is a choice....including breathing!"
      - "Reflect, reflect, REFLECT HARDER!!!"
      - "Face the monster...ME!"
      - "Keep your head on a swivel!"
      - "You have to build capacity"
      - "Practice perfectly"
      - "My record just increased"
      - "Did you write your TQPs?"
      - "You chose that? Come on, that's such a CT!!!"