settings:
  audio:
    enable_music: true
    enable_sfx: true
    vol_music: 0.6
    vol_sfx: 1.0
  fps:
    show: true
    value: 165
  fullscreen: false
  skip_intro: true
  fast_boot: true
  skip_enemies: false
other:
  chan_card_size:
  - 110
  - 165
  boss_face_size:
  - 500
  - 500
  highest_level_beat: 1
  last_level: 1
