settings:
  audio:
    enable_music: true
    enable_sfx: true
    music_vol: 1.0
    sfx_vol: 1.0
  fps:
    show: true
    value: 165
  fullscreen: false
  skip_intro: true
  faster_boot: true
other:
  chan_card_size:
  - 110
  - 165
  boss_face_size:
  - 500
  - 500
  highest_level_beat: 1
  last_level: 1
  effects:
    status:
    - fear
    - weakness
    - vulnerable
    - disappointment
    - marked
    - pained
    buff:
    - power
    - lifestyle
    - regeneration
    - energized
    - armor
    - clairvoyant
