settings:
  audio:
    enable_music: true
    enable_sfx: true
    music_vol: 1.0
    sfx_vol: 1.0
  fps:
    show: false
    value: 165
  fullscreen: false
  skip_intro: False
other:
  chan_card_size:
    - 110
    - 165
  boss_face_size:
    - 500
    - 500
  highest_level_beat: 1
  last_level: 1
  effects:
    status:
      - Fear
      - Weakness
      - Vulnerable
      - Disappointment
      - Marked
      - Pained
    buff:
      - Power
      - Lifesteal
      - Regeneration
      - Energized
      - Armor
      - Clairvoyant