settings:
  audio:
    enable_music: true
    enable_sfx: true
    music_vol: 1.0
    sfx_vol: 1.0
  fps:
    show: false
    value: 165
  fullscreen: false
other:
  chan_card_size:
    - 120
    - 180
  boss_face_size:
    - 500
    - 500
  highest_level_beat: 1